version: "3.8"

x-app: &app
  build: 
    context: .
    dockerfile: ./.docker/Dockerfile
    args:
      NODE_VERSION: 17.0.0
      PYTHON_VERSION: 3.9.2
      UBUNTU_VERSION: 20.04
      SEVERLESS_FRAMEWORK_VERSION: 3.7.4
  env_file:
    - ./.docker/.env
  volumes:
    - .:/app:cached
    - node_modules:/app/node_modules

services:
  offline:
    <<: *app
    command: >
      bash -c ".docker/bin/install &&
               yarn start --host 0.0.0.0"
    ports:
      - '3000:3000'

  serverless:
    <<: *app
    stdin_open: true
    tty: true
    environment:
      HISTFILE: .docker/.bash_history
    command: >
      bash -c ".docker/bin/version &&
               .docker/bin/install &&
               bash"

volumes:
  node_modules:
