version: "3.8"

x-app: &app
  build: 
    context: .
    dockerfile: ./.docker/offline/Dockerfile
    args:
      NODE_VERSION: '17.0.0'
      PYTHON_VERSION: '3.9.2'
      UBUNTU_VERSION: '21.10'
      SEVERLESS_FRAMEWORK_VERSION: '3.7.4'
  env_file:
    - ./.docker/.env
  volumes:
    - .docker/.bashrc:/root/.bashrc
    - .docker/.bash_history:/root/.bash_history
    - .:/app:cached
    - node_modules:/app/node_modules
    - dynamodb:/app/.dynamodb

services:
  offline:
    <<: *app
    command: >
      bash -c ".docker/bin/install_dependencies &&
               yarn start --host 0.0.0.0 --stage ${STAGE:-dev}"
    ports:
      - '3000:3000'

  dynamodb-admin:
    build: 
      context: .
      dockerfile: ./.docker/dynamodb-admin/Dockerfile
    env_file:
      - ./.docker/.env
    depends_on:
      - offline
    ports:
      - '8001:8001'

  serverless:
    <<: *app
    stdin_open: true
    tty: true
    environment:
      HISTFILE: /root/.bash_history
    command: >
      bash -c ".docker/bin/install_dependencies &&
               .docker/bin/setup_aws_cli &&
               .docker/bin/version &&
               bash"
    profiles:
      - development

volumes:
  node_modules:
  dynamodb:
